spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/todo
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB  # 이거 안해주면 디폴트가 1메가임
  mail:
    host: smtp.naver.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: mj17428@naver.com
    password: F8C3BEUDRBXG
    properties:
      mail:
        host: smtp.naver.com
        port: 587
        username: mj17428@naver.com
        password: F8C3BEUDRBXG
        properties:
          mail:
            transport:
              protocol: smtp
            smtp:
              auth: true  # SMTP 인증 사용
              starttls:
                enable: true  # STARTTLS 사용
                required: true
              ssl:
                trust: smtp.naver.com  # SSL 인증서 신뢰
                protocols: TLSv1.2
              debug: true  # 디버깅 정보 출력

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  dir: D:\postime\board\

---

spring:
  config:
    activate:
      on-profile: test

file:
  dir: D:\Students\MJ\download\greengram_ver2_1\